### ISSUE TITLE
Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by jmarkyston** [ANovokmet/svelte-gantt#209]
Hello, I'm attempting to use this in a Svelte component. I'm just trying to get the "dependencies" example working on my end: https://github.com/ANovokmet/svelte-gantt/blob/main/demo/src/routes/dependencies/%2Bpage.svelte

I've got the code set up in the same way as in the example, but whenever I initialize the chart, I get a `Cannot read properties of undefined (reading '$$')` error.

Do you have any idea what I'm missing?

Thanks, I'm looking forward to trying out this great tool!

**Comment by jmarkyston** [comment]
Interestingly, this same error also happens when using this in an Angular project. Maybe I'm missing a dependency or something, but I'm not sure what.

**Comment by ANovokmet** [comment]
Hmm, $$ is a svelte thing. But it should not be a concern because the library is also pre-built with it. If you're using svelte check the versions, if you're using angular, check that you're installing it with your package manager correctly.

If the issue is still happening, please post a repo reproducing it and I'll try to help more.
