### ISSUE TITLE
Row filtering 

### ISSUE THREAD

**Issue by Moxemka** [ANovokmet/svelte-gantt#211]
Hello,

Is there any solution for filtering columns

e. g.

I have rows and child rows

Parent1:
  Foo1,
  Foo2
Parent2:
 Foo1, 
 Foo3

After filtering by label parent1:
  Parent1
    Foo1, 
    Foo2
   
After filtering by Foo1:
  Parent1:
    Foo1, 
  Parent2:
   Foo1

Alredy tried:
  Getting rows from ctx, filter them, then using $set 

With this solution tasks dont stick to rows propperly and gantt throws an error in taskFactory.getHeight cant read height 

Also throws a critical error in dependency component when dependencies are present (cant read height in $$self.$$.update) 

What i need:

Tasks remain in gantt ctx, because i calculate interferance within different rows and I need tasks current positioning

Any solution would be helpful

**Comment by ANovokmet** [comment]
Because you're filtering rows, the old tasks can't find the now missing rows. I have to work on error handling here.

For now, until it is fixed, you can try filtering the tasks first, `$set`-ing the tasks, and setting the filtered rows next (maybe you will need to set the rows in a `setTimeout` call).

**Comment by ANovokmet** [comment]
In v4.3.0 tasks that reference rows that do not exist are allowed. When a row with the id appears, the tasks will then render appropriately.
