### ISSUE TITLE
Drag to Gantt does not round task time

### ISSUE THREAD

**Issue by ghost** [ANovokmet/svelte-gantt#27]
@ANovokmet When using `SvelteGanttExternal` to implement the functionality to drag a new task to the Gantt chart, it does not round/respect the default `magnetOffset` which is 15. For example, even on https://anovokmet.github.io/svelte-gantt/, if you use the drag to Gantt functionality, and try dragging it leaving the mouse somewhere in the middle of lines e.g. at 08:06am, this will work. And then the console log also proves this as well. So it is not respecting the default `magnetOffset`. However, afterwards, when moving the newly added task, it does respect it.

EDIT: Found another bug when dragging a new task to the Gantt:

When dragging a new task to the Gantt chart, by default, the colour whilst dragging is blue. However, when dropping the task i.e. letting go off the mouse, the task maybe a different colour like orange. Would be good if the task bar had the same colour whilst being dragging as it would when it is dropped.

**Comment by ANovokmet** [comment]
Hello, sorry I was not able to answer sooner.

In that example, instead of using the parameter `date` you can use the gantt like this `gantt.columnService.roundTo(date)`.

The blue color is dependent on the element created by `elementContent` which has a class that always makes the dragging indicator blue, but when the task is dropped it is created with a random color. Not a bug in the library, but how it's configured in the demo application. 

Fixing these is easy, but these two issues really concern only the demo.
