### ISSUE TITLE
[!] Error: Package subpath './compiler.js' is not defined by "exports" 

### ISSUE THREAD

**Issue by craigboman** [ANovokmet/svelte-gantt#86]
Running npm run demo:autobuild results in a something like an outdated npm package for rollup-plugin-svelte. Updating it from ^5.2.1 to 6.1.1 seems to resolve the outdated package but results in the following error which I'm not sure how to resolve.  

[!] Error: Package subpath './compiler.js' is not defined by "exports" 

Any ideas?

**Comment by V-Py** [comment]
Sorry just realizing I never answered on this issue. I have absolutely no idea, the packaging config isn't quite my speciality. Improving the Svelte/Typescript part isn't a problem, but for the packaging/building problems I'm really not a great help 😭

**Comment by Gismo150** [comment]
I had this issue too. It was fixed by updating the svelte package to a newer version in the package.json file. Currently it is on "svelte": "^3.23.0". Please try to update the svelte dependency to the latest version.

By updating the rollup-plugin-svelte to 6.1.1 you also need to update svelte due to a breaking change.

Here are more details:
https://stackoverflow.com/questions/66965954/build-error-after-updating-svelte-package-subpath-compiler-js-is-not-define

**Comment by V-Py** [comment]
Thanks for the infos, I'll give it a look

**Comment by ANovokmet** [comment]
In v4.1, versions of svelte, as the build process, has been updated, so this is likely fixed.
